backend:
  name: git-gateway
  branch: main  # 与仓库分支一致
media_folder: "source/images"
public_folder: "/images"
collections:
  - name: "posts"
    label: "Posts"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    fields:
      # 基础字段
      - { name: "title", label: "标题", widget: "string", required: true }
      - { name: "date", label: "发布日期", widget: "datetime", format: "YYYY-MM-DD", required: true }
      - { name: "tags", label: "标签", widget: "list", default: ["未分类"], required: false }
      
      # 新增字段
      - { name: "description", label: "文章摘要", widget: "text", required: false }
      - { name: "toc", label: "显示目录", widget: "boolean", default: true, required: false }
      
      # Markdown 正文
      - { name: "body", label: "正文内容", widget: "markdown", required: true }