backend:
  name: git-gateway
  branch: main

media_folder: "source/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "文章"
    folder: "source/_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: "md"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "描述", name: "description", widget: "string", required: false }
      - { label: "日期", name: "date", widget: "datetime" }
      - { label: "标签", name: "tags", widget: "list", required: false }
      - { label: "分类", name: "categories", widget: "string", required: false }
      - { label: "目录", name: "toc", widget: "boolean", default: true, required: false }
      - { label: "正文", name: "body", widget: "markdown" }